# Distance scale
# 149 597 870 700 metres = 1 AU = 1 distance unit = 1 * PixelsPerAU pixels
#
# Radius scale
# 12 756 km = 1 Earth diameter = 1 diameter unit
# x diameter units = BaseImageSize * log2(x + 1) pixels
# 
# Mass scale
# 5.974 * 10^24 kg = 1 Earth Mass = 1 mass unit

# start x and y are relative to parent body

# velocity vector is added to parent's velocity vector

repoURL: "http://mariallsmi.temp.swtest.ru/astroapp"

rock: "http://mariallsmi.temp.swtest.ru/astroapp/assets/rock.png"
arrow: "http://mariallsmi.temp.swtest.ru/astroapp/assets/blue_arrow.png"
background: "http://mariallsmi.temp.swtest.ru/astroapp/assets/background.png"

gConstant: 0.004 ## ???

bodies:
  - name: "sun"
    image: "http://mariallsmi.temp.swtest.ru/astroapp/assets/sun.png"
    mass: 330000
    diameter: 109
    x: 0
    y: 0
  - name: "mercury"
    parent: "sun"
    image: "http://mariallsmi.temp.swtest.ru/astroapp/assets/mercury.png"
    mass: 0.055
    diameter: 0.37629
    x: -0.387
    y: 0
    dx: 0
    dy: -0.055
  - name: "venus"
    parent: "sun"
    image: "http://mariallsmi.temp.swtest.ru/astroapp/assets/venus.png"
    mass: 0.815
    diameter: 0.948887
    x: 0
    y: 0.723
    dx: -0.0369
    dy: 0
  - name: "earth"
    parent: "sun"
    image: "http://mariallsmi.temp.swtest.ru/astroapp/assets/earth.png"
    mass: 1
    diameter: 1
    x: 1
    y: 0
    dx: 0
    dy: -0.0411
  - name: "mars"
    parent: "sun"
    image: "http://mariallsmi.temp.swtest.ru/astroapp/assets/mars.png"
    mass: 0.107
    diameter: 0.5326
    x: 1.524
    y: 0
    dx: 0
    dy: 0.029
  - name: "jupiter"
    parent: "sun"
    image: "http://mariallsmi.temp.swtest.ru/astroapp/assets/jupiter.png"
    mass: 318
    diameter: 11.2
    x: 5.203
    y: 0
    dx: 0
    dy: 0.018
  - name: "saturn"
    parent: "sun"
    image: "http://mariallsmi.temp.swtest.ru/astroapp/assets/saturn.png"
    mass: 95.2
    diameter: 9.449357
    x: 9.537
    y: 0
    dx: 0
    dy: 0.01
  - name: "uranus"
    parent: "sun"
    image: "http://mariallsmi.temp.swtest.ru/astroapp/assets/uranus.png"
    mass: 14.50
    diameter: 4.007
    x: 19.191
    y: 0
    dx: 0
    dy: 0.009
  - name: "neptune"
    parent: "sun"
    image: "http://mariallsmi.temp.swtest.ru/astroapp/assets/neptune.png"
    mass: 17.4
    diameter: 3.8827
    x: 30.069
    y: 0
    dx: 0
    dy: 0.005

